import { ExtractedField } from '../types';

export const INITIAL_EXTRACTED_FIELDS: ExtractedField[] = [
  {
    id: 'f_1',
    key: 'full_name',
    label: 'Full Name',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_2',
    key: 'father_name',
    label: 'Father / Husband Name',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_3',
    key: 'date_of_birth',
    label: 'Date of Birth (DD/MM/YYYY)',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_4',
    key: 'gender',
    label: 'Gender',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_5',
    key: 'aadhaar_number',
    label: 'Aadhaar Number (12 Digits)',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'IDENTIFICATION',
  },
  {
    id: 'f_6',
    key: 'pan_number',
    label: 'PAN Number (AAAAA9999A)',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'IDENTIFICATION',
  },
  {
    id: 'f_7',
    key: 'mobile_number',
    label: 'Mobile Contact Number',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_8',
    key: 'email',
    label: 'Email Address',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_9',
    key: 'address',
    label: 'Permanent Residential Address',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_10',
    key: 'city',
    label: 'City',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_11',
    key: 'state',
    label: 'State',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_12',
    key: 'pincode',
    label: 'Pincode (6 Digits)',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_13',
    key: 'annual_income',
    label: 'Annual Family Income',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_14',
    key: 'bank_account_number',
    label: 'Bank Account Number',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_15',
    key: 'ifsc_code',
    label: 'Bank IFSC Code',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_16',
    key: 'occupation',
    label: 'Occupation / Profession',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_17',
    key: 'marital_status',
    label: 'Marital Status',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_18',
    key: 'emergency_contact',
    label: 'Emergency Contact Number',
    value: '',
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
];
