import { ExtractedField } from '../types';

export const INITIAL_EXTRACTED_FIELDS: ExtractedField[] = [
  {
    id: 'f_1',
    key: 'full_name',
    label: 'Full Name',
    value: 'RAHUL VIKRAM VERMA',
    confidence: 98,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_2',
    key: 'father_name',
    label: 'Father / Husband Name',
    value: 'SURESH VERMA',
    confidence: 94,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_3',
    key: 'date_of_birth',
    label: 'Date of Birth (DD/MM/YYYY)',
    value: '14/08/1992',
    confidence: 96,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_4',
    key: 'gender',
    label: 'Gender',
    value: 'Male',
    confidence: 99,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_5',
    key: 'aadhaar_number',
    label: 'Aadhaar Number (12 Digits)',
    value: '4589 1029 3847',
    confidence: 99,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'IDENTIFICATION',
  },
  {
    id: 'f_6',
    key: 'pan_number',
    label: 'PAN Number (AAAAA9999A)',
    value: 'ABCDE1234F',
    confidence: 92,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'IDENTIFICATION',
  },
  {
    id: 'f_7',
    key: 'mobile_number',
    label: 'Mobile Contact Number',
    value: '+91 98765 43210',
    confidence: 95,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_8',
    key: 'email',
    label: 'Email Address',
    value: 'rahul.verma@gov.ai',
    confidence: 97,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_9',
    key: 'address',
    label: 'Permanent Residential Address',
    value: 'Flat 402, HighTech Heights, Silicon City, Whitefield, Bengaluru - 560066',
    confidence: 78,
    isMissing: false,
    isLowConfidence: true,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_10',
    key: 'city',
    label: 'City',
    value: 'Bengaluru',
    confidence: 94,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_11',
    key: 'state',
    label: 'State',
    value: 'Karnataka',
    confidence: 98,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_12',
    key: 'pincode',
    label: 'Pincode (6 Digits)',
    value: '560066',
    confidence: 96,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'ADDRESS',
  },
  {
    id: 'f_13',
    key: 'annual_income',
    label: 'Annual Family Income',
    value: 'INR 14,50,000',
    confidence: 92,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_14',
    key: 'bank_account_number',
    label: 'Bank Account Number',
    value: '', // Intentionally missing to test 🔴 Missing state
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_15',
    key: 'ifsc_code',
    label: 'Bank IFSC Code',
    value: '', // Intentionally missing to test 🔴 Missing state
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'TAX' as any,
  },
  {
    id: 'f_16',
    key: 'occupation',
    label: 'Occupation / Profession',
    value: 'Senior Software Engineer',
    confidence: 95,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_17',
    key: 'marital_status',
    label: 'Marital Status',
    value: 'Single',
    confidence: 98,
    isMissing: false,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
  {
    id: 'f_18',
    key: 'emergency_contact',
    label: 'Emergency Contact Number',
    value: '', // Intentionally missing to test 🔴 Missing state
    confidence: 0,
    isMissing: true,
    isLowConfidence: false,
    isRequired: true,
    category: 'PERSONAL',
  },
];
